#!/usr/bin/env bash

set -eux

source "${OPS_ROOT}"/helpers/snap-logger.sh "daemon"
source "${OPS_ROOT}"/helpers/snap-interfaces.sh


usage() {
cat << EOF
usage: start.sh --init-security yes --admin-password ...
To be ran / setup once per cluster.
--init-security   (Optional)    Enum of either: yes (default), no . Should be ran ONCE per cluster IF security enabled.
--admin-password  (Optional)    Passphrase of the admin key
--help                          Shows help menu
EOF
}


# Args
init_security=""
admin_password=""


# Args handling
function parse_args () {
    # init-security boolean - from the charm, this should be based on a flag on the app data bag.
    init_security="$(snapctl get init-security)"
    admin_password="$(snapctl get admin-password)"
}

function set_defaults () {
    if [ -z "${init_security}" ] || [ "${init_security}" != "no" ]; then
        init_security="yes"
    fi
}

function systemd_conf_override () {
    exit_if_missing_perm "systemd-write"

    DAEMON_SYSTEMD_PATH="/etc/systemd/system/snap.opensearch.daemon.service.d"
    [ -d "${DAEMON_SYSTEMD_PATH}" ] || mkdir -p "${DAEMON_SYSTEMD_PATH}"

    # We are copying the service conf file patch as editing the service file generated by snapd won't survive upgrades
    if [ ! -f "${DAEMON_SYSTEMD_PATH}"/override.conf ]; then
        cp "${SNAP}"/ops/sys/etc/systemd/override.conf "${DAEMON_SYSTEMD_PATH}"/
    fi
}

function system_proc_override () {
    # exit_if_missing_perm "proc-write"

    # 1. Set the number of open file handles
    # ulimit -n 1024 -- default in local machine
    ulimit -n 65535

    # 2. Allow the opensearch user to Disable all swap files:
    # swapon -a -- default in local machine
    sysctl -w vm.swappiness=0
    # echo 0 > /proc/sys/vm/swappiness

    # 3. Ensuring sufficient virtual memory: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
    # sysctl -w vm.max_map_count=65530 -- default in local machine
    sysctl -w vm.max_map_count=262144
    # echo 262144 > /proc/sys/vm/max_map_count

    # 4. number of threads opensearch can create:
    # should be configured automatically if opensearch ran as a service

    # 5. Reduce TCP retransmission timeout = ~6 seconds
    # sysctl -w net.ipv4.tcp_retries2=15 -- default in local machine
    sysctl -w net.ipv4.tcp_retries2=5
    # echo 5 > /proc/sys/net/ipv4/tcp_retries2
}


parse_args "$@"
set_defaults

systemd_conf_override
system_proc_override

# start
"${SNAP}"/usr/bin/setpriv \
    --clear-groups \
    --reuid snap_daemon \
    --regid snap_daemon -- \
    "${OPENSEARCH_HOME}"/bin/opensearch &

# give it some time to bootstrap
sleep 30s


if [ "${init_security}" == "yes" ]; then
    sec_args=(
        "-cd" "${OPENSEARCH_PATH_CONF}/opensearch-security/"
        "-icl" "-nhnv"
        "-cacert" "${OPENSEARCH_PATH_CERTS}/root-ca.pem"
        "-cert" "${OPENSEARCH_PATH_CERTS}/admin.pem"
        "-key" "${OPENSEARCH_PATH_CERTS}/admin-key.pem"
    )

    if [ -n "${admin_password}" ]; then
        sec_args+=("-keypass" "${admin_password}")
    fi

    source \
        "${OPENSEARCH_PLUGINS}/opensearch-security/tools/securityadmin.sh" \
        "${sec_args[@]}"
fi
