name: wazuh-indexer
base: core22

version: '4.8.2'

summary: OpenSearch with additional changes for easier use alongside Wazuh.
description: |
    Wazuh Indexer is a community-driven, Apache 2.0-licensed open source search and 
    analytics suite that makes it easy to ingest, search, visualize, and analyze data
    tailored for Wazuh.

grade: stable

confinement: devmode

architectures:
  - build-on: amd64

system-usernames:
  snap_daemon: shared

# TODO: build from sources
package-repositories:
  - type: apt
    components: [main]
    suites: [stable]
    key-id: 0DCFCA5547B19D2A6099506096B3EE5F29111145
    key-server: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    url: https://packages.wazuh.com/4.x/apt/

plugs:
  shmem-perf-analyzer:
    interface: shared-memory
    private: true
  sys-fs-cgroup-service:
    interface: system-files
    read:
      - /sys/fs/cgroup/system.slice/snap.wazuh-indexer.daemon.service


slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/wazuh-indexer


hooks:
  install:
    plugs:
      - network
      - network-bind
      - shmem-perf-analyzer
    environment:
      OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch

  configure:
    environment:
      OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch


environment:
  SNAP_CURRENT: /snap/wazuh-indexer/current
  SNAP_DATA_CURRENT: /var/snap/wazuh-indexer/current
  JAVA_HOME: ${SNAP}/usr/lib/jvm/java-21-openjdk-amd64
  PATH: ${JAVA_HOME}/jre/bin:$PATH
  HOME: ${SNAP_COMMON}/home/snap_daemon

  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs

  OPS_ROOT: ${SNAP_CURRENT}/opt/opensearch

  OPENSEARCH_BIN: ${SNAP_CURRENT}/usr/share/wazuh-indexer/bin
  OPENSEARCH_JAVA_HOME: ${JAVA_HOME}

  OPENSEARCH_HOME: ${SNAP_DATA_CURRENT}/usr/share/wazuh-indexer
  OPENSEARCH_LIB: ${OPENSEARCH_HOME}/lib
  OPENSEARCH_PLUGINS: ${OPENSEARCH_HOME}/plugins
  OPENSEARCH_MODULES: ${OPENSEARCH_HOME}/modules

  OPENSEARCH_PATH_CONF: ${SNAP_DATA_CURRENT}/etc/wazuh-indexer
  OPENSEARCH_PATH_CERTS: ${SNAP_DATA_CURRENT}/etc/wazuh-indexer/certificates

  OPENSEARCH_VARLIB: ${SNAP_COMMON}/var/lib/wazuh-indexer
  OPENSEARCH_TMPDIR: ${SNAP_COMMON}/usr/share/tmp
  OPENSEARCH_VARLOG: ${SNAP_COMMON}/var/log/wazuh-indexer

  KNN_LIB_DIR: ${OPENSEARCH_PLUGINS}/opensearch-knn/lib


apps:
  daemon:
    daemon: simple
    install-mode: disable
    command: opt/opensearch/start.sh
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind
      - hardware-observe
      - log-observe
      - mount-observe
      - process-control
      - shmem-perf-analyzer
      - system-observe
      - sys-fs-cgroup-service
    environment:
      LD_LIBRARY_PATH: "${LD_LIBRARY_PATH}:${KNN_LIB_DIR}:"

  security-init:
    command: opt/opensearch/security-init.sh
    plugs:
      - network
      - network-bind
    environment:
      JAVA_OPTS: ""

  setup:
    command: opt/opensearch/setup.sh

  plugin-add:
    command: opt/opensearch/plugins/add.sh

  plugins-list:
    command: opt/opensearch/plugins/list.sh

  plugins-remove:
    command: opt/opensearch/plugins/remove.sh

  test-cluster-health-green:
    command: opt/opensearch/tests/test-cluster-health-green.sh
    plugs:
      - network
      - network-bind

  test-node-up:
    command: opt/opensearch/tests/test-node-up.sh
    plugs:
      - network
      - network-bind

  test-security-index-created:
    command: opt/opensearch/tests/test-security-index-created.sh
    plugs:
      - network
      - network-bind

parts:
  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - util-linux
      - curl
      - procps
      - libfreetype6
      - libpng16-16
      - libxrender1
      - libx11-6
      - libxext6
      - libxi6
      - libxtst6
      - libpsm-infinipath1
      - libboost-all-dev
      - libpsm2-2-compat
      - libcrypt1
      - libexpat1
      - zlib1g

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/opt/opensearch"
      mkdir -p "${target_dir}"
      cp -r wrappers/. "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"

  wazuh-indexer:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-21-jdk
      - openssl
      - ssl-cert
    override-build: |
      # update deps
      apt-get update; apt-get upgrade -y; apt-get autoremove --purge -y; apt-get clean -y
      update-ca-certificates -f

      # setup trust store
      trust_store="${CRAFT_PART_INSTALL}/etc/ssl/certs/java/"
      mkdir -p "${trust_store}"
      cp /etc/ssl/certs/java/cacerts "${trust_store}"
    stage-packages:
      - openjdk-21-jdk
      - wazuh-indexer
    override-stage: |
      craftctl default
      chmod -R 755 usr/share/wazuh-indexer
      OPENSEARCH_PATH_CONF=${CRAFT_STAGE}/etc/wazuh-indexer ${CRAFT_STAGE}/usr/share/wazuh-indexer/bin/opensearch-plugin install --batch \
        https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/releases/download/2.13.0.0/prometheus-exporter-2.13.0.0.zip
      OPENSEARCH_PATH_CONF=${CRAFT_STAGE}/etc/wazuh-indexer ${CRAFT_STAGE}/usr/share/wazuh-indexer/bin/opensearch-plugin install --batch \
        https://artifacts.opensearch.org/releases/plugins/repository-gcs/2.13.0/repository-gcs-2.13.0.zip
      OPENSEARCH_PATH_CONF=${CRAFT_STAGE}/etc/wazuh-indexer ${CRAFT_STAGE}/usr/share/wazuh-indexer/bin/opensearch-plugin install --batch \
        https://artifacts.opensearch.org/releases/plugins/repository-s3/2.13.0/repository-s3-2.13.0.zip
      cp -r ${CRAFT_STAGE}/usr/share/wazuh-indexer/plugins/prometheus-exporter ${CRAFT_PART_INSTALL}/usr/share/wazuh-indexer/plugins/prometheus-exporter
      cp -r ${CRAFT_STAGE}/usr/share/wazuh-indexer/plugins/repository-gcs ${CRAFT_PART_INSTALL}/usr/share/wazuh-indexer/plugins/repository-gcs
      cp -r ${CRAFT_STAGE}/usr/share/wazuh-indexer/plugins/repository-s3 ${CRAFT_PART_INSTALL}/usr/share/wazuh-indexer/plugins/repository-s3
      # It is important to correnct the user permissions for the opensearch.keystore file, after the script is executed.
      # Given we know which user is going to be used for the daemon, we can set this correction in the keystore script.
      # TODO: we should perhaps NOT alter the source script - but until we find a better alternative UX wise we keep it
      echo 'chown snap_daemon:root /var/snap/wazuh-indexer/current/etc/wazuh-indexer/opensearch.keystore' >> "${CRAFT_STAGE}/usr/share/wazuh-indexer/bin/opensearch-keystore"
      sed -i -e 's/^\([^#].*\)/# \1/g' etc/wazuh-indexer/opensearch.yml
    override-prime: |
      craftctl default
      rm -rf usr/share/wazuh-indexer/jdk
