name: opensearch # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap

version: '2.9.0' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'OpenSearch: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
    OpenSearch is a community-driven, Apache 2.0-licensed open source search and 
    analytics suite that makes it easy to ingest, search, visualize, and analyze data. 
    Developers build with OpenSearch for use cases such as application search, 
    log analytics, data observability, data ingestion, and more.

grade: stable # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


system-usernames:
  snap_daemon: shared


plugs:
  sys-fs-cgroup-service:
    interface: system-files
    read:
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service

hooks:
  install:
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops

  configure:
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops


environment:
  OPS_ROOT: ${SNAP}/usr/share/ops
  OPENSEARCH_BIN: ${SNAP}/usr/share/opensearch/bin
  OPENSEARCH_JAVA_HOME: ${SNAP}/usr/share/opensearch/jdk

  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs
  OPENSEARCH_VARLIB: ${SNAP_COMMON}/var/lib/opensearch
  OPENSEARCH_TMPDIR: ${SNAP_COMMON}/usr/share/tmp
  OPENSEARCH_VARLOG: ${SNAP_COMMON}/var/log/opensearch

  OPENSEARCH_PATH_CONF: /var/snap/opensearch/current/etc/opensearch
  OPENSEARCH_HOME: /var/snap/opensearch/current/usr/share/opensearch
  OPENSEARCH_LIB: /var/snap/opensearch/current/usr/share/opensearch/lib
  OPENSEARCH_PLUGINS: /var/snap/opensearch/current/usr/share/opensearch/plugins
  OPENSEARCH_MODULES: /var/snap/opensearch/current/usr/share/opensearch/modules

  OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  KNN_LIB_DIR: ${OPENSEARCH_PLUGINS}/opensearch-knn/lib

  KNN_LIB_DIR: ${OPENSEARCH_PLUGINS}/opensearch-knn/lib

apps:
  daemon:
    daemon: simple
    install-mode: disable
    command: usr/share/ops/start.sh
    restart-condition: always
    restart-delay: 20s
    # reload-command: ${SNAP}/usr/share/ops/start.sh
    plugs:
      - network
      - network-bind
      - log-observe
      - mount-observe
      - process-control
      - system-observe
      - sys-fs-cgroup-service
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates
      LD_LIBRARY_PATH: "${LD_LIBRARY_PATH}:${KNN_LIB_DIR}"

  security-init:
    command: usr/share/ops/security-init.sh
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates
      JAVA_OPTS: ""

  setup:
    command: usr/share/ops/setup.sh
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  test-cluster-health-green:
    command: usr/share/ops/tests/test-cluster-health-green.sh
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  test-node-up:
    command: usr/share/ops/tests/test-node-up.sh
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  test-security-index-created:
    command: usr/share/ops/tests/test-security-index-created.sh
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/usr/share/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

parts:
  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - util-linux
      - curl
      - procps
      - libfreetype6
      - libpng16-16
      - libxrender1
      - libx11-6
      - libxext6
      - libxi6
      - libxtst6
      - libpsm-infinipath1
      - libboost-all-dev
      - libasound2
      - libpsm2-2-compat
      - libcrypt1
      - libexpat1
      - zlib1g

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/usr/share/ops"
      mkdir -p "${target_dir}"
      cp -r wrappers/. "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"
      rm -rf wrappers/ helpers/

  opensearch:
    plugin: nil
    override-build: |
        version="$(craftctl get version)"
        archive="opensearch-${version}-linux-x64.tar.gz"
      
        curl -o "${archive}" "https://artifacts.opensearch.org/releases/bundle/opensearch/${version}/${archive}"
        tar -xzvf "${archive}" -C "${CRAFT_PART_INSTALL}/" --strip-components=1
      
        mkdir -p "${CRAFT_PART_INSTALL}/usr/share/opensearch"

        # OPENSEARCH_HOME points to SNAP_DATA, whereas the /bin folder sits in /snap
        sed -i 's@OPENSEARCH_CLASSPATH=\"\$OPENSEARCH_HOME/lib/\*\"@if \[\[ -z "$OPENSEARCH_CLASSPATH" \]\]; then OPENSEARCH_CLASSPATH=\"\$OPENSEARCH_LIB\"/*; fi@g' "${CRAFT_PART_INSTALL}"/bin/opensearch-env
        sed -i 's@bin/opensearch-keystore@\"\${OPENSEARCH_BIN}\"/opensearch-keystore@' "${CRAFT_PART_INSTALL}"/bin/opensearch

        declare -a dirs=(bin jdk lib modules plugins config performance-analyzer-rca)
        for dir in "${dirs[@]}"; do
            target_dir="${CRAFT_PART_INSTALL}/usr/share/opensearch/${dir}"
            mv "${CRAFT_PART_INSTALL}/${dir}" "${target_dir}"
            chmod -R 755 "${target_dir}"
        done

        # It is important to correct the user permissions for the opensearch.keystore file, after the script is executed.
        # Given we know which user is going to be used for the daemon, we can set this correction in the keystore script.
        echo 'chown snap_daemon:snap_daemon /var/snap/opensearch/current/etc/opensearch/opensearch.keystore || true' >> "${CRAFT_PART_INSTALL}"/usr/share/opensearch/bin/opensearch-keystore

        # Final clean-up
        rm "${archive}"
        rm -rf "${CRAFT_PART_INSTALL}/"LICENSE.txt "${CRAFT_PART_INSTALL}/"manifest.yml "${CRAFT_PART_INSTALL}/"logs/ "${CRAFT_PART_INSTALL}/"NOTICE.txt "${CRAFT_PART_INSTALL}/"opensearch-tar-install.sh "${CRAFT_PART_INSTALL}/"README.md
