name: opensearch # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap

version: '2.2.1' # just for humans, typically '1.2+git' or '1.3.2'

summary: 'OpenSearch: community-driven, Apache 2.0-licensed search and analytics suite.'
description: |
    OpenSearch is a community-driven, Apache 2.0-licensed open source search and 
    analytics suite that makes it easy to ingest, search, visualize, and analyze data. 
    Developers build with OpenSearch for use cases such as application search, 
    log analytics, data observability, data ingestion, and more.

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


system-usernames:
  snap_daemon: shared


plugs:
  procsys-read:
    interface: system-files
    read:
      - /proc/cgroups
      - /proc/self/coredump_filter
      - /proc/sys/vm/max_map_count
      - /proc/sys/vm/swappiness
      - /proc/sys/net/ipv4/tcp_retries2
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.controllers
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.events
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.freeze
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.max.depth
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.max.descendants
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.procs
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.stat
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.subtree_control
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.threads
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cgroup.type
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.idle
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.max
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.max.burst
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.pressure
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpuset.cpus
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpuset.cpus.effective
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpuset.cpus.partition
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpuset.mems
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpuset.mems.effective
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.stat
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.uclamp.max
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.uclamp.min
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.weight
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/cpu.weight.nice
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/io.max
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/io.pressure
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/io.prio.class
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/io.stat
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/io.weight
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.current
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.events
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.events.local
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.high
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.low
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.max
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.min
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.numa_stat
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.oom.group
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.pressure
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.stat
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.swap.current
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.swap.events
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.swap.high
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/memory.swap.max
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/pids.current
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/pids.events
      - /sys/fs/cgroup/system.slice/snap.opensearch.daemon.service/pids.max

hooks:
  install:
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/ops

  configure:
    environment:
      OPS_ROOT: ${SNAP}/ops


environment:
  SNAP_LOG_DIR: ${SNAP_COMMON}/ops/snap/logs

  OPENSEARCH_HOME: ${SNAP_DATA}
  OPENSEARCH_JAVA_HOME: ${SNAP_DATA}/jdk
  OPENSEARCH_PATH_CONF: ${SNAP_COMMON}/config
  OPENSEARCH_TMPDIR: ${SNAP_COMMON}/tmp
  OPENSEARCH_PLUGINS: ${SNAP_DATA}/plugins

apps:
  daemon:
    daemon: simple
    install-mode: disable
    command: ops/start.sh
    # reload-command: ops/start.sh
    plugs:
      - network
      - network-bind
      - log-observe
      - mount-observe
      - process-control
      - procsys-read
      - system-observe
    environment:
      OPS_ROOT: ${SNAP}/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  security-init:
    command: ops/security-init.sh
    plugs:
      - network
      - network-bind
    environment:
      OPS_ROOT: ${SNAP}/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates
      JAVA_OPTS: ""

  setup:
    command: ops/setup.sh
    environment:
      OPS_ROOT: ${SNAP}/ops
      OPENSEARCH_PATH_CERTS: ${OPENSEARCH_PATH_CONF}/certificates

  plugin-add:
    command: ops/plugins/add.sh

  plugins-list:
    command: ops/plugins/list.sh

  plugins-remove:
    command: ops/plugins/remove.sh

parts:
  dependencies:
    plugin: nil
    stage-snaps:
      - yq
    stage-packages:
      - util-linux
      - procps
      - libfreetype6
      - libpng16-16
      - libxrender1
      - libx11-6
      - libxext6
      - libxi6
      - libxtst6
      - libpsm-infinipath1
      - libboost-all-dev
      - libasound2
      - libpsm2-2-compat
      - libcrypt1
      - libexpat1
      - zlib1g

  wrapper-scripts:
    plugin: nil
    source: ./scripts
    source-type: local
    override-build: |
      target_dir="${CRAFT_PART_INSTALL}/ops"
      
      rm -rf "${target_dir}"
      
      cp -r wrappers/. "${target_dir}"
      cp -r helpers/ "${target_dir}/helpers"

  opensearch:
    plugin: nil
    override-build: |
        version="$(craftctl get version)"
        archive="opensearch-${version}-linux-x64.tar.gz"
      
        curl -o "${archive}" "https://artifacts.opensearch.org/releases/bundle/opensearch/${version}/${archive}"
        tar -xzvf "${archive}" -C "${CRAFT_PART_INSTALL}/" --strip-components=1
