name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
  pull_request:

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install required dependencies
        run: |
          sudo snap install yq

      - name: Upgrade linux deps
        run: |
          sudo apt-get update
          
          # install security updates
          sudo apt-get -s dist-upgrade \
            | grep "^Inst" \
            | grep -i securi \
            | awk -F " " {'print $2'} \
            | xargs sudo apt-get install -y
          
          sudo apt-get autoremove -y

      - id: build-snap
        name: Build snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/candidate

      - name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: "opensearch_*.snap"

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_snap_amd64
          path: .

      - name: Setup snap file
        run: tox -e snap-setup -f {tox_root}/snap/snapcraft.yaml

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Ensure the cluster is reachable and node created
        run: tox -e check-snap-install

      - name: Install backup plugin and configure it
        env:
          OPENSEARCH_JAVA_HOME: /snap/opensearch/current/usr/share/opensearch/jdk
          OPENSEARCH_BIN: /snap/opensearch/current/usr/share/opensearch/bin
          OPENSEARCH_PATH_CONF: /var/snap/opensearch/current/etc/opensearch
          OPENSEARCH_HOME: /var/snap/opensearch/current/usr/share/opensearch
          OPENSEARCH_LIB: /var/snap/opensearch/current/usr/share/opensearch/lib
          OPENSEARCH_PATH_CERTS: /var/snap/opensearch/current/etc/opensearch/certificates
        run: tox -e install-backup

      - name: Upgrade snap
        run: tox -e upgrade-to-local-snap -- -f {tox_root}/snap/snapcraft.yaml -c x2

      - name: Remove backup plugin
        env:
          OPENSEARCH_JAVA_HOME: /snap/opensearch/current/usr/share/opensearch/jdk
          OPENSEARCH_BIN: /snap/opensearch/current/usr/share/opensearch/bin
          OPENSEARCH_PATH_CONF: /var/snap/opensearch/current/etc/opensearch
          OPENSEARCH_HOME: /var/snap/opensearch/current/usr/share/opensearch
          OPENSEARCH_LIB: /var/snap/opensearch/current/usr/share/opensearch/lib
          OPENSEARCH_PATH_CERTS: /var/snap/opensearch/current/etc/opensearch/certificates
        run: tox -e remove-backup
