name: Build and Test
on:
  push:
    branches:
      - main
      - edge
      - track/**
      - feature/**

jobs:
  build-run-tests:
    name: Build and Run Tests
    uses: ./.github/workflows/ci.yaml
