name: Publish to Snap Store

env:
  RELEASE: edge

on:
  push:
    branches:
      - '2/edge'
      - 'test/2.19.4'
  workflow_call:
  workflow_dispatch:

jobs:
  ci-tests:
    name: Build and Run Tests
    uses: ./.github/workflows/ci.yaml

  build-snaps:
    name: Build snap | 2.19.4
    strategy:
      fail-fast: false
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v49.0.2
    with:
      path-to-snap-project-directory: .
      artifact-prefix: packed-snap-opensearch
    permissions:
      actions: read # Needed for GitHub API call to get workflow version
      contents: read

  publish-snaps:
    name: Publish snap to PR branch | OpenSearch 2.19.4
    needs:
      - build-snaps
    strategy:
      fail-fast: false
    uses: canonical/data-platform-workflows/.github/workflows/release_snap_pr.yaml@v49.0.2
    with:
      track: 2
      path-to-snap-project-directory: .
      artifact-prefix: packed-snap-opensearch
    secrets:
      snap-store-token: ${{ secrets.STORE_LOGIN }}
    permissions:
      actions: read   # Needed for GitHub API call to get workflow version
      contents: read
