#!/usr/bin/env bash

set -eux


source "${OPS_ROOT}"/helpers/snap-logger.sh "hook-install"
source "${OPS_ROOT}"/helpers/io.sh
source "${OPS_ROOT}"/helpers/set-conf.sh


function create_file_structure () {
    ETC="${SNAP_DATA}/etc/opensearch"
    USR="${SNAP_DATA}/usr/share/opensearch"

    # Opensearch install folders and set config
    add_folder "${USR}" 770
    add_folder "${USR}/extensions" 770
    add_file "${USR}/extensions/extensions.yml" 770

    add_folder "${SNAP_DATA}/etc" 770

    ls -al "${SNAP}"
    pushd "${SNAP}/opensearch"
    ls -al
    dir_copy_if_not_exists "plugins" "${USR}" 770
    ls -la "${USR}"
    ls -la "${USR}/plugins"
    ls -la "${USR}/plugins/opensearch-reports-scheduler"
    dir_contents_copy "config" "${ETC}" 770
    ls -al "${ETC}"
    popd
    add_folder "${ETC}/certificates" 770
    add_file "${ETC}/unicast_hosts.txt" 770

    add_folder "${SNAP_COMMON}/var/lib/opensearch" 770
    add_folder "${SNAP_COMMON}/var/log/opensearch" 774
    add_folder "${SNAP_COMMON}/tmp" 770
}


function set_base_config_props () {
    # Change conf to set log and data paths for both opensearch.yml and jvm.options
    set_yaml_prop "${ETC}/opensearch.yml" "path.data" "${SNAP_COMMON}/var/lib/opensearch"
    set_yaml_prop "${ETC}/opensearch.yml" "path.logs" "${SNAP_COMMON}/var/log/opensearch"

    replace_in_file "${ETC}/jvm.options" "=logs/" "=${SNAP_COMMON}/var/log/opensearch"
}

create_file_structure
set_base_config_props
