#!/usr/bin/env bash

set -eux

OLD_SNAP_DATA=$(cat "${SNAP_COMMON}"/on_refresh_snap)
rm "${SNAP_COMMON}"/on_refresh_snap

for i in $(find "${SNAP_DATA}"/etc/opensearch -type f); do
        # Some files may have been created by snap_daemon and then, will cause permission denied
	if sed "s@${OLD_SNAP_DATA}@${SNAP_DATA}@g" $i > "$SNAP_DATA"/temp_sed_file; then
		cat "$SNAP_DATA"/temp_sed_file > $i
	fi
done

rm "$SNAP_DATA"/temp_sed_file
